version: "3"

services:
  mysql:
    image: mysql:5.7
    ports:
      - 13370:3306
    container_name: mysql
    volumes:
      - ./components/mysql/data:/var/lib/mysql
      - ./components/mysql/conf/my.conf:/etc/my.cnf
      - /etc/localtime:/etc/localtime
      - ./components/mysql/init:/docker-entrypoint-initdb.d/"
    environment:
      MYSQL_ROOT_PASSWORD: 	175a8d1e
      MYSQL_USER: 'admin'
      MYSQL_PASS: '175a8d1e'
    restart: always