mysql:
  dbMysqlAddress: [ 127.0.0.1:13370 ] #mysql地址 目前仅支持单机，默认即可
  dbMysqlUserName: root #mysql用户名，建议修改
  dbMysqlPassword: 175a8d1e # mysql密码，建议修改
  dbMysqlDatabaseName: excel_props #默认即可
  dbTableName: eMsg #默认即可
  dbMsgTableNum: 1
  dbMaxOpenConns: 100
  dbMaxIdleConns: 10
  dbMaxLifeTime: 5
  logLevel: 1 #1=slient 2=error 3=warn 4=info
  slowThreshold: 500
redis:
  dbAddress: [ 127.0.0.1:16380 ] #redis地址 单机时，填写一个地址即可，使用redis集群时候，填写集群中多个节点地址（主从地址都可以填写，增加容灾能力），默认即可
  dbMaxIdle: 128
  dbMaxActive: 0
  dbIdleTimeout: 120
  dbUserName:     #only redis version 6.0+ need username
  dbPassWord: 175a8d1e #redis密码 建议修改
  enableCluster: false #如果外部redis以集群方式启动，需要打开此开关

api:
  apiPort: [ 45001 ] #api服务端口，默认即可，需要开放此端口或做nginx转发
  listenIP: 0.0.0.0
manager:
  #app管理员userID和对应的secret 用于客户端登录
  appManagerUid: [ "admin1","admin2", "admin3", "admin4"]
  secrets: [ "admin1","admin2", "admin3", "admin4"]
#token config
tokenpolicy:
  accessSecret: "excel_props" #token生成相关，默认即可
  # Token effective time day as a unit
  accessExpire: 180 #token过期时间（天） 默认即可
